
security:
  oauth2:
    client:
      client-id: 73fd74c4dfd3
      client-secret: 0bc2b785d173419ca4e0948c90896b06
      scope: read,write
      auto-approve-scopes: '.*'
server:
  port: 8089
logging:
  level:
    org.springframework: DEBUG



spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth_test?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
